[package]
name = "rust-stacks"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bip39 = "1.0"
secp256k1 = "0.20"
bitcoin = "0.27"

[[bin]]
name = "create_address"
path = "./src/createAddress.rs"